/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AntAlert: typeof import('antd')['Alert']
  const AntBreadcrumb: typeof import('antd')['Breadcrumb']
  const AntButton: typeof import('antd')['Button']
  const AntCheckbox: typeof import('antd')['Checkbox']
  const AntCollapse: typeof import('antd')['Collapse']
  const AntDatePicker: typeof import('antd')['DatePicker']
  const AntLayout: typeof import('antd')['Layout']
  const AntMenu: typeof import('antd')['Menu']
  const AntPagination: typeof import('antd')['Pagination']
  const AntTable: typeof import('antd')['Table']
  const ConfigProvider: typeof import('antd')['ConfigProvider']
  const StrictMode: typeof import('react')['StrictMode']
  const Suspense: typeof import('react')['Suspense']
  const cloneElement: typeof import('react')['cloneElement']
  const createContext: typeof import('react')['createContext']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
